.PHONY: all format lint test tests integration_tests help extended_tests ci \
        pre-commit-install pre-commit-run pre-commit-uninstall

# Default target executed when no arguments are given to make.
all: help

# Define a variable for the test file path.
TEST_FILE ?= tests/unit_tests/
integration_test integration_tests: TEST_FILE = tests/integration_tests/


# unit tests are run with the --disable-socket flag to prevent network calls
test tests:
	poetry run pytest --disable-socket --allow-unix-socket $(TEST_FILE)

test_watch:
	poetry run ptw --snapshot-update --now . -- -vv $(TEST_FILE)

# integration tests are run without the --disable-socket flag to allow network calls
integration_test integration_tests:
	poetry run pytest $(TEST_FILE)

######################
# LINTING AND FORMATTING
######################

# Define a variable for Python and notebook files.
PYTHON_FILES=.
MYPY_CACHE=.mypy_cache
lint format: PYTHON_FILES=.
lint_diff format_diff: PYTHON_FILES=$(shell git diff --relative=libs/partners/githubcopilot-chat --name-only --diff-filter=d master | grep -E '\.py$$|\.ipynb$$')
lint_package: PYTHON_FILES=langchain_githubcopilot_chat
lint_tests: PYTHON_FILES=tests
lint_tests: MYPY_CACHE=.mypy_cache_test

lint lint_diff lint_package lint_tests:
	[ "$(PYTHON_FILES)" = "" ] || poetry run ruff check $(PYTHON_FILES)
	[ "$(PYTHON_FILES)" = "" ] || poetry run ruff format $(PYTHON_FILES) --diff
	[ "$(PYTHON_FILES)" = "" ] || mkdir -p $(MYPY_CACHE) && poetry run mypy $(PYTHON_FILES) --cache-dir $(MYPY_CACHE)

format format_diff:
	[ "$(PYTHON_FILES)" = "" ] || poetry run ruff format $(PYTHON_FILES)
	[ "$(PYTHON_FILES)" = "" ] || poetry run ruff check --fix $(PYTHON_FILES)

spell_check:
	poetry run codespell --toml pyproject.toml

spell_fix:
	poetry run codespell --toml pyproject.toml -w

check_imports: $(shell find langchain_githubcopilot_chat -name '*.py')
	poetry run python ./scripts/check_imports.py $^

######################
# LOCAL CI SIMULATION
# Mirrors the exact steps run in .github/workflows/ci.yml so you can
# catch failures before pushing.
#
# Usage:
#   make ci            # run all three CI jobs locally
#   make ci_lint       # lint job only
#   make ci_test       # unit-test job only
#   make ci_spell      # spell-check job only
######################

ci: ci_lint ci_test ci_spell
	@echo ''
	@echo '================================'
	@echo '  All local CI checks passed!  '
	@echo '================================'

ci_lint:
	@echo '--- [CI] Installing lint + typing deps ---'
	poetry install --no-interaction --with lint,typing
	@echo '--- [CI] ruff check ---'
	poetry run ruff check .
	@echo '--- [CI] ruff format --diff ---'
	poetry run ruff format . --diff
	@echo '--- [CI] mypy ---'
	mkdir -p .mypy_cache
	poetry run mypy langchain_githubcopilot_chat --cache-dir .mypy_cache

ci_test:
	@echo '--- [CI] Installing test deps ---'
	poetry install --no-interaction --with test
	@echo '--- [CI] pytest unit tests ---'
	poetry run pytest --disable-socket --allow-unix-socket tests/unit_tests/ -v

ci_spell:
	@echo '--- [CI] Installing codespell deps ---'
	poetry install --no-interaction --with codespell
	@echo '--- [CI] codespell ---'
	poetry run codespell --toml pyproject.toml

######################
# PRE-COMMIT
# Installs a git pre-push hook that runs `make ci` automatically
# before every `git push`, blocking the push if any check fails.
#
# Usage:
#   make pre-commit-install    # install the git hook
#   make pre-commit-run        # run hooks manually (without pushing)
#   make pre-commit-uninstall  # remove the git hook
######################

pre-commit-install:
	@echo '--- Installing pre-push git hook ---'
	@mkdir -p .git/hooks
	@printf '#!/bin/sh\n\
# Auto-generated by: make pre-commit-install\n\
# Runs local CI checks before every git push.\n\
set -e\n\
echo "[pre-push] Running local CI checks (make ci)..."\n\
make ci\n\
echo "[pre-push] All checks passed. Proceeding with push."\n' > .git/hooks/pre-push
	@chmod +x .git/hooks/pre-push
	@echo 'pre-push hook installed at .git/hooks/pre-push'
	@echo 'It will run `make ci` automatically before every `git push`.'

pre-commit-run:
	@echo '--- Running pre-push checks manually ---'
	@make ci

pre-commit-uninstall:
	@echo '--- Removing pre-push git hook ---'
	@rm -f .git/hooks/pre-push
	@echo 'pre-push hook removed.'

######################
# HELP
######################

help:
	@echo '----'
	@echo 'check_imports                - check imports'
	@echo 'format                       - run code formatters'
	@echo 'lint                         - run linters'
	@echo 'test                         - run unit tests'
	@echo 'tests                        - run unit tests'
	@echo 'test TEST_FILE=<test_file>   - run all tests in file'
	@echo '---'
	@echo 'ci                           - run ALL local CI checks (lint + test + spell)'
	@echo 'ci_lint                      - run lint CI job locally'
	@echo 'ci_test                      - run unit-test CI job locally'
	@echo 'ci_spell                     - run spell-check CI job locally'
	@echo '---'
	@echo 'pre-commit-install           - install git pre-push hook (runs make ci before push)'
	@echo 'pre-commit-run               - run pre-push checks manually'
	@echo 'pre-commit-uninstall         - remove git pre-push hook'
